import pandas as pd


res = [
    ['Afghan Restaurant', 0],
    ['American Restaurant', 0],
    ['Asian Restaurant', 0],
    ['BBQ Joint', 0],
    ['Bagel Shop', 0],
    ['Bakery', 0],
    ['Bar', 0],
    ['Beer Bar', 0],
    ['Breakfast Spot', 0],
    ['Brewery', 0],
    ['Bubble Tea Shop', 0],
    ['Burger Joint', 0],
    ['Café', 0],
    ['Cajun / Creole Restaurant', 0],,
    ['Chinese Restaurant', 0],
    ['Cocktail Bar', 0],
    ['Coffee Shop', 0],
    ['College Cafeteria', 0],
    ['Creperie', 0],
    ['Cuban Restaurant', 0],
    ['Cupcake Shop', 0],
    ['Deli / Bodega', 0],
    ['Dive Bar', 0],
    ['Doner Restaurant', 0],
    ['Donut Shop', 0],
    ['Ethiopian Restaurant', 0],
    ['Farmers Market', 0],
    ['Fast Food Restaurant', 0],
    ['Fish Market', 0],
    ['Food', 0],
    ['Food & Drink Shop', 0],
    ['Food Truck', 0],
    ['French Restaurant', 0],
    ['Fried Chicken Joint', 0],
    ['Gastropub', 0],
    ['Greek Restaurant', 0],
    ['Hot Dog Joint', 0],
    ['Hotel Bar', 0],
    ['Ice Cream Shop', 0],
    ['Indian Restaurant', 0],
    ['Irish Pub', 0],
    ['Italian Restaurant', 0],
    ['Japanese Restaurant', 0],
    ['Juice Bar', 0],
    ['Mediterranean Restaurant', 0],
    ['Mexican Restaurant', 0],
    ['New American Restaurant', 0],
    ['Noodle House', 0],
    ['Peruvian Restaurant', 0],
    ['Pizza Place', 0],
    ['Portuguese Restaurant', 0],
    ['Pub', 0],
    ['Restaurant', 0],
    ['Salvadoran Restaurant', 0],
    ['Sandwich Place', 0],
    ['Seafood Restaurant', 0],
    ['Southern / Soul Food Restaurant', 0],
    ['Speakeasy', 0],
    ['Steakhouse', 0],
    ['Sushi Restaurant', 0],
    ['Taco Place', 0],
    ['Tex-Mex Restaurant', 0],
    ['Thai Restaurant', 0],
    ['Theme Restaurant', 0],
    ['Vegetarian / Vegan Restaurant', 0],
    ['Vietnamese Restaurant', 0],
    ['Wine Bar', 0]
]